In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((10,5 ))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [10]:
np.eye(4) # matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand()

0.15379166966704583

In [12]:
np.random.rand(4)

array([0.41868607, 0.76798648, 0.4403882 , 0.64134669])

In [13]:
np.random.rand(4,4)

array([[0.73569751, 0.96781128, 0.09755705, 0.43879692],
       [0.37897644, 0.23124335, 0.36458313, 0.17167086],
       [0.93348947, 0.44271544, 0.05851833, 0.57895439],
       [0.72726588, 0.89589839, 0.43015492, 0.91068006]])

In [14]:
np.random.randint(1,15)

8

In [15]:
np.random.randint(1,100, (10,10))# se le pasa la estructura que se quiere manejar

array([[87, 24, 45, 61, 60, 72, 24, 16, 18, 82],
       [42, 24,  7, 63, 81, 12, 87, 72, 90,  8],
       [ 9, 69, 53, 90, 12, 50, 57, 18, 14, 52],
       [21, 21, 56, 58, 24, 10,  1, 90, 61, 13],
       [28, 74, 23, 60, 62, 64, 61, 28, 58, 81],
       [58, 18, 95, 56, 47, 13, 99, 31, 41, 54],
       [48, 75,  7, 50,  8, 51, 94, 32, 36, 14],
       [47, 13, 94, 86, 93, 77, 74, 66,  6, 36],
       [10, 30, 96, 76, 26, 24, 69, 24, 30, 65],
       [85, 26, 46, 41, 34,  7, 78, 57, 81, 11]])