In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[19, 10, 14,  1, 11],
       [ 5, 10, 18,  1,  9]])

## Maximo

In [5]:
arr.max()

19

In [7]:
matriz.max()

19

In [8]:
matriz.max(1)# para cada fila(1), nos coge el maximo

array([19, 18])

In [9]:
matriz.max(0)# 0, por columnas

array([19, 10, 18,  1, 11])

In [10]:
arr.argmax() # el indice donde se encuentra el maximo

0

In [11]:
matriz.argmax(0)

array([0, 0, 1, 0, 0])

## Minimo

In [12]:
arr.min()

1

In [13]:
arr.argmin()

3

In [15]:
matriz.min(0)

array([ 5, 10, 14,  1,  9])

In [16]:
matriz.argmin(1)

array([3, 3])

## Diferencia del valor más grande al más pequeño(pick to pick).

In [17]:
arr

array([19, 10, 14,  1, 11,  5, 10, 18,  1,  9])

In [19]:
arr.ptp()

18

In [21]:
matriz.ptp(0)

array([14,  0,  4,  0,  2])

## Percentiles

In [23]:
np.percentile(arr, 50) # mediana

10.0

## Ordenar

In [25]:
arr.sort()
arr

array([ 1,  1,  5,  9, 10, 10, 11, 14, 18, 19])

## Mediana

In [26]:
np.median(arr)

10.0

## Varianza

In [28]:
np.var(arr)

34.96

## Desviación tipica

In [27]:
np.std(arr)

5.912698199637793

## Media

In [29]:
np.mean(arr)

9.8

## Concatenate

In [30]:
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])

In [31]:
#np.concatenate((a,b), axis=0)
# las dimensiones de a y b deben ser iguales
b = np.expand_dims(b, axis=0)
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
# np.concatenate((a,b), axis=1)
# para poder hacerlo por colunmas b debe ser una columna, para cumplir las dimensiones
np.concatenate((a,b.T), axis=1) # hacemos la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])