In [3]:
import numpy as np

Numpy array de 1 dimensión

In [1]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr = np.array(lista)
type(arr)

numpy.ndarray

Numpy array de 2 dimensiones

In [7]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexin

In [10]:
print(arr)
print(arr[0])

[1 2 3 4 5 6 7 8 9]
1


In [11]:
arr[0]+arr[5]

7

In [12]:
print(matriz)
matriz[0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

In [13]:
matriz[0,2]

3

Slicing

In [18]:
arr[0:3]

array([1, 2, 3])

In [19]:
arr[0:11] # no out of bounds

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[:6] # arranca desde el comienzo

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[2:] # hasta el final

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[::2] # se puede realizar por pasos

array([1, 3, 5, 7, 9])

In [23]:
arr[-3:] # se empieza contando desde atras

array([7, 8, 9])

In [24]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])