In [1]:
import numpy as np

In [2]:
arr = np.random.randint(2,20,(3,2))

In [3]:
arr

array([[13, 18],
       [18,  2],
       [14, 11]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.reshape(1,6)

array([[13, 18, 18,  2, 14, 11]])

In [6]:
arr.reshape(2,3)

array([[13, 18, 18],
       [ 2, 14, 11]])

In [7]:
np.reshape(arr, (1,6))

array([[13, 18, 18,  2, 14, 11]])

In [8]:
arr

array([[13, 18],
       [18,  2],
       [14, 11]])

In [9]:
np.reshape(arr, (2,3), 'C') # Como lo hace C, tomando por filas

array([[13, 18, 18],
       [ 2, 14, 11]])

In [10]:
np.reshape(arr, (2,3), 'F')# Como lo hace fortrant, cogiendo por columnas

array([[13, 14,  2],
       [18, 18, 11]])

In [11]:
np.reshape(arr, (2,3), 'A') # Segun la forma de guardado de mi laptop
# mejor forma para optimizar tiempo
# de normal C, que es como lo hace python

array([[13, 18, 18],
       [ 2, 14, 11]])