In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int64')

Cambio tipo de datos

In [4]:
arr = np.array([1,2,3,4], dtype='float64')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [6]:
arr = np.array([1,2,3,4])
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [7]:
arr = np.array([0, 1,2,3,4])
arr = arr.astype(np.bool_)
print(arr)
print(arr.dtype)
# en boolean el 0 siempre es falso, mientras que el resto verdadero

[False  True  True  True  True]
bool


In [8]:
arr = np.array([0, 1,2,3,4])
arr = arr.astype(np.string_)
print(arr)
print(arr.dtype)
# En string los maneja como cadenas de caracteres

[b'0' b'1' b'2' b'3' b'4']
|S21


In [9]:
arr = np.array(['0', '1','2','3','4'])
arr = arr.astype(np.int8)
print(arr)
print(arr.dtype)
# Es capaz de coger los numeros que son string a int
# pero falla si intenta convertir caracteres a numeros

[0 1 2 3 4]
int8


El array de numpy debe tener todos los elementos del mismo tipo, si no fallará